# Generated by Django 4.0.5 on 2022-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review_counts',
        ),
        migrations.AddField(
            model_name='product',
            name='last_rank',
            field=models.IntegerField(default=999999, verbose_name='最新排名'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_review_count',
            field=models.IntegerField(default=0, verbose_name='最新评论数'),
        ),
        migrations.AddField(
            model_name='sellerbase',
            name='last_days_30_ratings',
            field=models.IntegerField(default=0, verbose_name='30天fd数'),
        ),
        migrations.AddField(
            model_name='sellerbase',
            name='last_days_90_ratings',
            field=models.IntegerField(default=0, verbose_name='90天fd数'),
        ),
        migrations.AddField(
            model_name='sellerbase',
            name='last_life_ratings',
            field=models.IntegerField(default=0, verbose_name='总fd数'),
        ),
        migrations.AddField(
            model_name='sellerbase',
            name='last_product_counts',
            field=models.IntegerField(default=0, verbose_name='产品数'),
        ),
        migrations.AddField(
            model_name='sellerbase',
            name='last_year_ratings',
            field=models.IntegerField(default=0, verbose_name='一年fd数'),
        ),
    ]
