# Generated by Django 3.2.13 on 2022-07-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220708_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品基础数据', 'verbose_name_plural': '产品基础数据'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': '产品排名数据', 'verbose_name_plural': '产品排名数据'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '产品评论数据', 'verbose_name_plural': '产品评论数据'},
        ),
        migrations.AlterModelOptions(
            name='sellerbase',
            options={'verbose_name': '卖家基础信息', 'verbose_name_plural': '卖家基础信息'},
        ),
        migrations.AlterModelOptions(
            name='sellerdetail',
            options={'verbose_name': '卖家历史数据', 'verbose_name_plural': '卖家历史数据'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': '关键词', 'verbose_name_plural': '关键词'},
        ),
        migrations.AlterModelOptions(
            name='wordship',
            options={'verbose_name': '关键词关联数据', 'verbose_name_plural': '关键词关联数据'},
        ),
        migrations.AddField(
            model_name='word',
            name='search_product_results',
            field=models.IntegerField(default=0, verbose_name='搜索产品总数'),
        ),
        migrations.AddField(
            model_name='word',
            name='search_products_review_counts',
            field=models.IntegerField(default=0, verbose_name='搜索产品总评论数'),
        ),
    ]
