# Generated by Django 4.0.5 on 2022-07-10 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220708_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_url', models.CharField(max_length=300, verbose_name='初始链接地址')),
                ('start_page', models.IntegerField(default=0, verbose_name='开始页数')),
                ('end_page', models.IntegerField(default=200, verbose_name='结束页数')),
                ('replace_pattern', models.CharField(max_length=10, verbose_name='页码替换字符')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'verbose_name': '抓取链接信息',
            },
        ),
    ]
