# Generated by Django 4.0.5 on 2022-07-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': '抓取链接信息', 'verbose_name_plural': '抓取链接信息'},
        ),
        migrations.AlterField(
            model_name='url',
            name='replace_pattern',
            field=models.CharField(default='{page}', max_length=10, verbose_name='页码替换字符'),
        ),
    ]
