# Generated by Django 4.0.5 on 2022-07-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_url_options_alter_url_replace_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='replace_pattern',
        ),
        migrations.AddField(
            model_name='url',
            name='page_replace_pattern',
            field=models.CharField(default='<page>', max_length=10, verbose_name='上一页替换字符'),
        ),
        migrations.AddField(
            model_name='url',
            name='pre_page_replace_pattern',
            field=models.CharField(default='<pre_page>', max_length=20, verbose_name='上一页替换字符'),
        ),
    ]
