# Generated by Django 4.0.5 on 2022-07-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_url_start_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=500, verbose_name='标题'),
        ),
    ]
