# Generated by Django 4.0.5 on 2022-07-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_type', models.CharField(default='cat', max_length=20, verbose_name='url类型')),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='url_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.urltype'),
            preserve_default=False,
        ),
    ]
