# Generated by Django 4.0.5 on 2022-07-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_url_url_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url_type',
            new_name='urltype',
        ),
    ]
