# Generated by Django 4.0.5 on 2022-07-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_urltype_comment_alter_url_urltype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urltype',
            options={'verbose_name': '抓取链接类型', 'verbose_name_plural': '抓取链接类型'},
        ),
        migrations.AddField(
            model_name='url',
            name='last_crawl_time',
            field=models.DateTimeField(default='', verbose_name='上次抓取时间'),
        ),
    ]
