# Generated by Django 4.0.5 on 2022-07-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_urltype_options_url_last_crawl_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='last_crawl_time',
            field=models.DateTimeField(default='1990-01-01 00:00', verbose_name='上次抓取时间'),
        ),
    ]
