# Generated by Django 4.0.5 on 2022-07-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_url_last_crawl_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='last_crawl_time',
        ),
    ]
